- hosts: xweb
  user: bryan
  become: true
  tasks:
    - name: Ping all hosts
      ping:

    - name: disable selinux
      selinux:
        state: disabled
    
    - name: XWeb packages are installed
      yum:
        name: 
          - wget
          - nano 
          - git
          - nginx
          - nfs-utils
        state: present
        update_cache: true
   
    - name: Create mnt nasbox directory
      ansible.builtin.file:
        path: /mnt/nasbox
        state: directory
        mode: '0755'

    - name: stop/disable firewalld
      ansible.builtin.service: 
        name: firewalld
        state: stopped
        masked: yes

    - name: disable firewalld
      ansible.builtin.service: 
        name: firewalld
        enabled: no

    - name: Create nginx sites directory
      ansible.builtin.file:
        path: /etc/nginx/sites
        state: directory
        mode: '0755'

    - name: Copy repo conf to remote
      ansible.builtin.copy:
        src: files/repo.conf
        dest: /etc/nginx/sites/repo.conf
        owner: root
        group: root
        mode: '0644'
    
    - name: copy nginx fancy module
      ansible.builtin.copy:
        src: files/ngx_http_fancyindex_module.so
        dest: /usr/share/nginx/modules/ngx_http_fancyindex_module.so
        owner: root
        mode: '0644'

    - name: Copy nginx.conf to remote
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

    - name: start/enable nginx
      ansible.builtin.service: 
        name: nginx
        state: started
        masked: no

    - name: enable nginx
      ansible.builtin.service: 
        name: nginx
        enabled: yes
