---
# tasks file for roles/zk

- name: Check for zk role
  stat:
    path: /opt/roles/zk
  register: zkRole

# create zk user
- name: Create zk group
  become: true
  ansible.builtin.group:
    name: zk
    state: present
    gid: 2000

- name: Add zk user
  become: true
  ansible.builtin.user:
    name: zk
    shell: /bin/bash
    uid: 2000
    groups: zk
    append: yes

# mkdir /opt/zk
- name: Create /opt/zk directory
  become: true
  ansible.builtin.file:
    path: /opt/zk
    state: directory
    owner: zk
    group: zk
    mode: '0755'

# grab zk from apache site
- name: Download zookeeper from Apache
  become: yes
  get_url:
    url: https://ftp.wayne.edu/apache/zookeeper/zookeeper-3.6.3/apache-zookeeper-3.6.3-bin.tar.gz
    dest: /opt/zk
    mode: 0755
    group: zk
    owner: zk
  when: zkRole.stat.exists == false  

#extract zk to /opt/zk/
- name: Extract ZK
  become: true
  command: "tar zxf /opt/zk/apache-zookeeper-3.6.3-bin.tar.gz -C /opt/zk/"
  when: zkRole.stat.exists == false

- name: rename directory
  become: true
  command: mv /opt/zk/apache-zookeeper-3.6.3-bin /opt/zk/zk-3.6.3
  when: zkRole.stat.exists == false

- name: Fix /opt/zk perms
  become: true
  ansible.builtin.file:
    path: /opt/zk/zk-3.6.3
    state: directory
    recurse: yes
    owner: zk
    group: zk
    mode: '0755'

# tweak conf file
- name: Zookeeper properties file
  become: yes
  ansible.builtin.template:
    src: templates/zookeeper.j2
    dest: /opt/zk/zk-3.6.3/conf/zoo.cfg
    owner: zk
    group: zk
    mode: '0644'
  when: zkRole.stat.exists == false

# build unit file
- name: Zookeeper unit file
  become: yes
  ansible.builtin.template:
    src: templates/zk.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: '0644'
  when: zkRole.stat.exists == false

# mkdir /opt/zk/zk-3.6.3
- name: Create /opt/zk/zk-3.6.3/data
  become: true
  ansible.builtin.file:
    path: /opt/zk/zk-3.6.3/data
    state: directory
    owner: zk
    group: zk
    mode: '0755'
  when: zkRole.stat.exists == false

# tweak myid file
- name: Zookeeper myid file
  become: yes
  ansible.builtin.template:
    src: templates/myid.j2
    dest: /opt/zk/zk-3.6.3/data/myid
    owner: zk
    group: zk
    mode: '0644'
  when: zkRole.stat.exists == false

# reload systemd
- name: Reload Systemd
  become: yes
  command: systemctl daemon-reload

# start zk
- name: Start Zookeeper
  ansible.builtin.service:
    name: zookeeper
    state: started

- name: Create Roles directory
  become: true
  ansible.builtin.file:
    path: /opt/roles
    state: directory
    owner: root
    mode: '0644'

- name: Drop zk role file
  become: true
  ansible.builtin.file:
    path: /opt/roles/zk
    state: touch
    owner: root
    mode: '0644'