---
# tasks file for roles/updates
- name: update the system
  dnf:
    name: "*"
    state: latest

- name: Add the user 'jenkins' with a specific uid
  ansible.builtin.user:
    name: jenkins
    comment: Build User
    uid: 1040
    group: wheel