---
- hosts: bind
  become: true

  tasks:
     - name: Upgrade all packages, excluding kernel & foo related packages
       yum:
         name: '*'
         state: latest
         exclude: kernel*,foo*         
